CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "login" varchar NOT NULL,
  "name" varchar NOT NULL,
  "birthday" date NOT NULL
);

CREATE TABLE IF NOT EXISTS "genres"(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "rating" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "films" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar DEFAULT 'Описание отсутсвует',
  "rating_id" integer NOT NULL REFERENCES "rating" ("id"),
  "release_date" date NOT NULL,
  "duration" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "film_genres"(
  "film_id" integer REFERENCES "films" ("id"),
  "genre_id" integer REFERENCES "genres" ("id")
);

CREATE TABLE IF NOT EXISTS "friends" (
  "requested_user_id" integer REFERENCES "users" ("id"),
  "receiving_user_id" integer NOT NULL REFERENCES "users" ("id"),
  "status" varchar
);

CREATE TABLE IF NOT EXISTS "likes" (
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "film_id" integer NOT NULL REFERENCES "films" ("id")
);